version: '3.0'

networks:
  crv_dev_network:
    driver: bridge

services:
  db-dev:
    container_name: mysql-dev
    image: mysql:5.7.17
    env_file:
      - ./.env
    volumes:
      - ./volumes/mysql/dev/database:/var/lib/mysql
      - ./volumes/mysql/dev/conf:/etc/mysql/conf.d
    networks:
      crv_dev_network:
        aliases:
          - mysql
    ports:
      - "3307:3306"

  app-dev:
    container_name: symfony-app-dev
    image: fiser/phpdddstandar-symfony-app:dev
# For locale image deploy
#    build:
#      context: ../
#      dockerfile: ./Docker/php/dev/Dockerfile
    volumes:
      - ../:/app
    networks:
      crv_dev_network:
        aliases:
          - php
    env_file:
      - ./.env

  nginx-dev:
    container_name: nginx-server-dev
    image: fiser/phpdddstandar-nginx:dev
# For locale image deploy
#    build:
#      context: nginx/dev
#      dockerfile: Dockerfile

    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ../.:/app
      - ./volumes/log/dev/Nginx:/var/log/nginx
    networks:
      crv_dev_network:
        aliases:
          - nginx